# GENERAL & NAVs
site_name: Plexosoft Docs
nav:
  - Home: index.md
  - Design:
      - Overview: design/overview.md
      - Design Thinking:
          - Overview: design/design-thinking/overview.md
          - Idea Outline: design/design-thinking/idea-outline/idea_outline.md
          - Empathy: design/design-thinking/empathy/empathy.md
          - Personas: design/design-thinking/personas/personas.md
          - Definition: design/design-thinking/definition/definition.md
          - Persona: design/design-thinking/persona/persona.md
          - Ideate: design/design-thinking/ideate/ideate.md
          - Conclusion: design/design-thinking/conclusion/conclusion.md
          - PoC Prototype: design/design-thinking/PoC/poc.md
      - User-Centric Design:
          - Overview: design/user-centric/overview.md
          - Strategy: design/user-centric/strategy/strategy.md
          - Scope: design/user-centric/scope/scope.md
          - Structure: design/user-centric/structure/structure.md
          - Skeleton: design/user-centric/skeleton/skeleton.md
          - Surface: design/user-centric/surface/surface.md
      - Entity Relationship Diagram ERD:
          - ERD: design/erd/erd.md
      - Web Marketing Strategy:
          - Overview: design/web-marketing/overview.md
          - Strategy Plan: design/web-marketing/strategy_plan.md
          - Actions Taken: design/web-marketing/actions_taken.md
  - Development:
      - Agile Development: development/agile-development/agile_development.md
      - Bug, Testing & Security: development/bug-test-security/bug_test_security.md
  - Features:
      - Actual Features: features/actual-features/actual_features.md
      - Future Features: features/future-features/future_features.md
  - Tech:
      - Technologies Used: tech/tech_used.md
  - Initialize:
      - Set Up & Deployment: initialize/setup_and_deployment.md
  - Snack:
      - Overview: snack/developer-snack/overview.md
      - Make Documentation: snack/mkdoc/mkdoc.md
      - Django Admin & Summernote: snack/developer-snack/development_reminder.md
      - Google Auth Installation: snack/developer-snack/google_auth.md
      - Common Bugs: snack/developer-snack/common_bugs.md
      - Naming Convention: snack/developer-snack/naming_convention.md
      - Lambda Convention: snack/developer-snack/lambda.md
      - Database & Django Shell: snack/developer-snack/shell_database.md
  - About:
      - Plexosoft Docs: about/about.md
      - License: about/LICENSE.md
  - Credits: credits/credits.md

# PLUGINS (bug present as not installed)
# plugins:
#   - glightbox

# THEME
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: green
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: indigo

# EXTRA
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/plexoio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plexoio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arellanofrank/

# EXTENSIONS
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # COPYRIGHT


copyright: |
  &copy; 2023 by <a href="https://github.com/plexoio"  target="_blank" rel="noopener">Frank Arellano</a> 
  with 
  <a href="https://www.mkdocs.org/"  target="_blank" rel="noopener">MkDocs</a>
